name: Workflow 1

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Job 1
        run: echo "Workflow 1 running"

      - run: sleep 10
