name: Last Flow

on:
  workflow_run:
    workflows: ["Third Flow"]
    types: [completed]

jobs:
  second-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello World
        run: echo "Hello World"