name: Workflow 2

on:
  pull_request:
    branches:
      - main

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Workflow 1
        run: |
          echo "Waiting for Workflow 1 to succeed..."
          while ! gh run list --json status --jq '.[] | select(.name=="Workflow 1") | .status' | grep -q "completed"; do
            sleep 5
          done
          if ! gh run list --json conclusion --jq '.[] | select(.name=="Workflow 1") | .conclusion' | grep -q "success"; then
            echo "Workflow 1 failed, exiting."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Job 2
        run: echo "Workflow 2 running"
