name: Second Flow

# on:
#   workflow_run:
#     workflows: ["GitHub Actions Demo"]
#     types: [completed]

jobs:
  second-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello World
        run: echo "Hello World"
