name: Third Flow

# on:
#   workflow_run:
#     workflows: ["Second Flow"]
#     types: [completed]
on: 
  push:
    branches:
      - "development"
      - "main"
  pull_request:
    branches:
      - "development"
      - "main"
jobs:
  third-job:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello World
        run: echo "hi"
