name: Third Flow

on:
  workflow_run:
    workflows: ["Second Flow"]
    types: [completed]

jobs:
  third-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello World
        run: echo "hi"
