name: Third Flow

on:
  workflow_run:
    workflows: ["Second Flow"]
    types: [completed]

  pull_request:
    branches:
      - "development"
      - "main"

jobs:
  second-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello World
        run: sdjfsjkdfh